config/routes.rb
Rails.application.routes.draw do
  resources :ators
  resources :filmes
  resources :papels
  resources :personagems
  resources :estudios

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  has_many :Filmes
end

app/controllers/estudios_controller.rb
class EstudiosController < ApplicationController
  before_action :set_estudio, only: [:show, :edit, :update, :destroy]

  # GET /estudios
  # GET /estudios.json
  def index
    @estudios = Estudio.all
  end

  # GET /estudios/1
  # GET /estudios/1.json
  def show
  end

  # GET /estudios/new
  def new
    @estudio = Estudio.new
  end

  # GET /estudios/1/edit
  def edit
  end

  # POST /estudios
  # POST /estudios.json
  def create
    @estudio = Estudio.new(estudio_params)

    respond_to do |format|
      if @estudio.save
        format.html { redirect_to @estudio, notice: 'Estudio was successfully created.' }
        format.json { render :show, status: :created, location: @estudio }
      else
        format.html { render :new }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudios/1
  # PATCH/PUT /estudios/1.json
  def update
    respond_to do |format|
      if @estudio.update(estudio_params)
        format.html { redirect_to @estudio, notice: 'Estudio was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudio }
      else
        format.html { render :edit }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudios/1
  # DELETE /estudios/1.json
  def destroy
    @estudio.destroy
    respond_to do |format|
      format.html { redirect_to estudios_url, notice: 'Estudio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudio
      @estudio = Estudio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudio_params
      params.require(:estudio).permit(:nome, :nome_dono, :data_fundacao, :faturamento)
    end
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/views/estudios/_form.html.erb
<%= form_with(model: estudio, local: true) do |form| %>
  <% if estudio.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert" id="error_explanation">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h2><%= pluralize(estudio.errors.count, "error") %> prohibited this estudio from being saved:</h2>
    <ul>
      <% estudio.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-box">
    <div class="form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, id: :estudio_nome, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :nome_dono %>
      <%= form.text_field :nome_dono, id: :estudio_nome_dono, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :data_fundacao %>
      <%= form.date_select :data_fundacao, id: :estudio_data_fundacao, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :faturamento %>
      <%= form.text_field :faturamento, id: :estudio_faturamento, class:'form-control' %>
    </div>
    <div class="actions">
      <%= form.submit class:'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/estudios/edit.html.erb
<div class="container">
  <h1 class="text-center">Editing Estudio</h1>

  <%= render 'form', estudio: @estudio %>

  <%= link_to 'Show', @estudio %> |
  <%= link_to 'Back', estudios_path %>
</div>

app/views/estudios/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid table-div">
  <h1 class="table-title text-center">Estudios</h1>
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-striped text-center">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Nome dono</th>
          <th>Data fundacao</th>
          <th>Faturamento</th>
          <th colspan="3">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @estudios.each do |estudio| %>
          <tr>
            <td><%= estudio.nome %></td>
            <td><%= estudio.nome_dono %></td>
            <td><%= estudio.data_fundacao %></td>
            <td><%= estudio.faturamento %></td>
            <td><%= link_to 'Show', estudio %></td>
            <td><%= link_to 'Edit', edit_estudio_path(estudio) %></td>
            <td><%= link_to 'Destroy', estudio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to '<span class="fa fa-plus"></span> New Estudio'.html_safe, new_estudio_path, class:'btn btn-info' %>
</div>

app/views/estudios/new.html.erb
<div class="container">
  <h1 class="text-center">New Estudio</h1>

  <%= render 'form', estudio: @estudio %>

  <%= link_to 'Back', estudios_path %>

</div>

app/views/estudios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estudio.nome %>
</p>

<p>
  <strong>Nome dono:</strong>
  <%= @estudio.nome_dono %>
</p>

<p>
  <strong>Data fundacao:</strong>
  <%= @estudio.data_fundacao %>
</p>

<p>
  <strong>Faturamento:</strong>
  <%= @estudio.faturamento %>
</p>

<%= link_to 'Edit', edit_estudio_path(@estudio) %> |
<%= link_to 'Back', estudios_path %>