config/routes.rb
Rails.application.routes.draw do
  resources :ators
  resources :filmes
  resources :papels
  resources :personagems
  resources :estudios

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ator.rb
class Ator < ApplicationRecord
  has_many :Papels
  has_many :Personagems
end

app/controllers/ators_controller.rb
class AtorsController < ApplicationController
  before_action :set_ator, only: [:show, :edit, :update, :destroy]

  # GET /ators
  # GET /ators.json
  def index
    @ators = Ator.all
  end

  # GET /ators/1
  # GET /ators/1.json
  def show
  end

  # GET /ators/new
  def new
    @ator = Ator.new
  end

  # GET /ators/1/edit
  def edit
  end

  # POST /ators
  # POST /ators.json
  def create
    @ator = Ator.new(ator_params)

    respond_to do |format|
      if @ator.save
        format.html { redirect_to @ator, notice: 'Ator was successfully created.' }
        format.json { render :show, status: :created, location: @ator }
      else
        format.html { render :new }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ators/1
  # PATCH/PUT /ators/1.json
  def update
    respond_to do |format|
      if @ator.update(ator_params)
        format.html { redirect_to @ator, notice: 'Ator was successfully updated.' }
        format.json { render :show, status: :ok, location: @ator }
      else
        format.html { render :edit }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ators/1
  # DELETE /ators/1.json
  def destroy
    @ator.destroy
    respond_to do |format|
      format.html { redirect_to ators_url, notice: 'Ator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ator
      @ator = Ator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ator_params
      params.require(:ator).permit(:nome, :nome_artistico, :seguro_social, :nacionalidade, :idade)
    end
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/views/ators/_form.html.erb
<%= form_with(model: ator, local: true) do |form| %>
  <% if ator.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2><%= pluralize(ator.errors.count, "error") %> prohibited this ator from being saved:</h2>
      <ul>
        <% ator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-box">
    <div class="form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, id: :ator_nome, class:'form-control', placeholder:'placeholder' %>
    </div>
    <div class="form-group">
      <%= form.label :nome_artistico %>
      <%= form.text_field :nome_artistico, id: :ator_nome_artistico, class:'form-control', placeholder:'placeholder' %>
    </div>
    <div class="form-group">
      <%= form.label :seguro_social %>
      <%= form.number_field :seguro_social, id: :ator_seguro_social, class:'form-control', placeholder:'placeholder' %>
    </div>
    <div class="form-group">
      <%= form.label :nacionalidade %>
      <%= form.text_field :nacionalidade, id: :ator_nacionalidade, class:'form-control', placeholder:'placeholder' %>
    </div>
    <div class="form-group">
      <%= form.label :idade %>
      <%= form.text_field :idade, id: :ator_idade, class:'form-control', placeholder:'placeholder' %>
    </div>
    <div class="actions">
      <%= form.submit class:'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/ators/edit.html.erb
<div class="container">
  <h1 class="text-center">Editing Ator</h1>

  <%= render 'form', ator: @ator %>

  <%= link_to 'Show', @ator %> |
  <%= link_to 'Back', ators_path %>
</div>

app/views/ators/index.html.erb
<div class="container-fluid table-div">
  <p id="notice"><%= notice %></p>
  <h1>Ators</h1>
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-striped text-center">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Nome artistico</th>
          <th>Seguro social</th>
          <th>Nacionalidade</th>
          <th>Idade</th>
          <th colspan="3">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @ators.each do |ator| %>
          <tr>
            <td><%= ator.nome %></td>
            <td><%= ator.nome_artistico %></td>
            <td><%= ator.seguro_social %></td>
            <td><%= ator.nacionalidade %></td>
            <td><%= ator.idade %></td>
            <td><%= link_to 'Show', ator %></td>
            <td><%= link_to 'Edit', edit_ator_path(ator) %></td>
            <td><%= link_to 'Destroy', ator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to '<span class="fa fa-plus"></span> New Ator'.html_safe, new_ator_path, class:'btn btn-info' %>
</div>

app/views/ators/new.html.erb
<div class="container">
  <h1 class="text-center">New Ator</h1>

  <%= render 'form', ator: @ator %>

  <%= link_to 'Back', ators_path %>

</div>

app/views/ators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ator.nome %>
</p>

<p>
  <strong>Nome artistico:</strong>
  <%= @ator.nome_artistico %>
</p>

<p>
  <strong>Seguro social:</strong>
  <%= @ator.seguro_social %>
</p>

<p>
  <strong>Nacionalidade:</strong>
  <%= @ator.nacionalidade %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @ator.idade %>
</p>

<%= link_to 'Edit', edit_ator_path(@ator) %> |
<%= link_to 'Back', ators_path %>