config/routes.rb
Rails.application.routes.draw do
  resources :ators
  resources :filmes
  resources :papels
  resources :personagems
  resources :estudios

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <h5 class="text-center text-muted">
      <span class="fa fa-database"></span>
      laboratório de bancos de dados 2017.2
    </h5>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" name="menu" class="navbar-toggle collapse"
          data-toggle="collapse" data-target="#menu-list" aria-expanded="false">
        <span class="glyphicon glyphicon-menu"></span>
      </button>
      <%= link_to 'REDIS on ma Rails', root_path, class:'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="#menu-list">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "ESTUDIOS", estudios_path, class:"navbar-link"%>
        </li>
        <li>
          <%= link_to "FILMES", filmes_path, class:"navbar-link"%>
        </li>
        <li>
          <%= link_to "ATORES", ators_path, class:"navbar-link"%>
        </li>
        <li>
          <%= link_to "PAPEIS", papels_path, class:"navbar-link"%>
        </li>
        <li>
          <%= link_to "PERSONAGENS", personagems_path, class:"navbar-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hollywood</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width: device-width, initial-scale: 1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>