config/routes.rb
Rails.application.routes.draw do
  resources :ators
  resources :filmes
  resources :papels
  resources :personagems
  resources :estudios

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/personagem.rb
class Personagem < ApplicationRecord
  belongs_to :ator
end

app/controllers/personagems_controller.rb
class PersonagemsController < ApplicationController
  before_action :set_personagem, only: [:show, :edit, :update, :destroy]

  # GET /personagems
  # GET /personagems.json
  def index
    @personagems = Personagem.all
  end

  # GET /personagems/1
  # GET /personagems/1.json
  def show
  end

  # GET /personagems/new
  def new
    @personagem = Personagem.new
  end

  # GET /personagems/1/edit
  def edit
  end

  # POST /personagems
  # POST /personagems.json
  def create
    @personagem = Personagem.new(personagem_params)

    respond_to do |format|
      if @personagem.save
        format.html { redirect_to @personagem, notice: 'Personagem was successfully created.' }
        format.json { render :show, status: :created, location: @personagem }
      else
        format.html { render :new }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personagems/1
  # PATCH/PUT /personagems/1.json
  def update
    respond_to do |format|
      if @personagem.update(personagem_params)
        format.html { redirect_to @personagem, notice: 'Personagem was successfully updated.' }
        format.json { render :show, status: :ok, location: @personagem }
      else
        format.html { render :edit }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personagems/1
  # DELETE /personagems/1.json
  def destroy
    @personagem.destroy
    respond_to do |format|
      format.html { redirect_to personagems_url, notice: 'Personagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personagem
      @personagem = Personagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personagem_params
      params.require(:personagem).permit(:nome, :nome_filme, :nome_ator, :cache_ator)
    end
end

app/helpers/personagems_helper.rb
module PersonagemsHelper
end

app/views/personagems/_form.html.erb
<%= form_with(model: personagem, local: true) do |form| %>
  <% if personagem.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert" id="error_explanation">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h2><%= pluralize(personagem.errors.count, "error") %> prohibited this personagem from being saved:</h2>
    <ul>
      <% personagem.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-box">
    <div class="form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, id: :personagem_nome, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :nome_filme %>
      <%= form.text_field :nome_filme, id: :personagem_nome_filme, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :nome_ator %>
      <%= form.text_field :nome_ator, id: :personagem_nome_ator, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :cache_ator %>
      <%= form.text_field :cache_ator, id: :personagem_cache_ator, class:'form-control' %>
    </div>
    <div class="actions">
      <%= form.submit class:'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/personagems/edit.html.erb
<div class="container">
  <h1 class="text-center">Editing Personagem</h1>

  <%= render 'form', personagem: @personagem %>

  <%= link_to 'Show', @personagem %> |
  <%= link_to 'Back', personagems_path %>

</div>

app/views/personagems/index.html.erb
<div class="container-fluid table-div">
  <p id="notice"><%= notice %></p>
  <h1>Personagems</h1>
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-striped text-center">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Nome filme</th>
          <th>Nome ator</th>
          <th>Cache ator</th>
          <th colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @personagems.each do |personagem| %>
        <tr>
          <td><%= personagem.nome %></td>
          <td><%= personagem.nome_filme %></td>
          <td><%= personagem.nome_ator %></td>
          <td><%= personagem.cache_ator %></td>
          <td><%= link_to 'Show', personagem %></td>
          <td><%= link_to 'Edit', edit_personagem_path(personagem) %></td>
          <td><%= link_to 'Destroy', personagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to '<span class="fa fa-plus"></span> New Personagem'.html_safe, new_personagem_path, class:'btn btn-info' %>
</div>

app/views/personagems/new.html.erb
<div class="container">
  <h1 class="text-center">New Personagem</h1>

  <%= render 'form', personagem: @personagem %>

  <%= link_to 'Back', personagems_path %>

</div>

app/views/personagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @personagem.nome %>
</p>

<p>
  <strong>Nome filme:</strong>
  <%= @personagem.nome_filme %>
</p>

<p>
  <strong>Nome ator:</strong>
  <%= @personagem.nome_ator %>
</p>

<p>
  <strong>Cache ator:</strong>
  <%= @personagem.cache_ator %>
</p>

<%= link_to 'Edit', edit_personagem_path(@personagem) %> |
<%= link_to 'Back', personagems_path %>